account/urls.py
from django.urls import path
from django.contrib.auth import views

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

task/urls.py
from django.urls import path
from task import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('done/<int:pk>/', views.done, name='done'),
    path('incomplete/<int:pk>/', views.incomplete, name='incomplete'),
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('task.urls')),
    path('account/', include('account.urls')),
    
]

task/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

def get_max_order_num(user):
    tasks = Task.objects.filter(author=user)
    if not tasks:
        return - 1
    return max(list(map(lambda x: x.order_num, tasks)))

class Task(models.Model):
    objects = models.Manager()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True)
    title = models.CharField(_('Title'), max_length=200,)
    text = models.TextField()
    is_done = models.BooleanField(default=False,)
    is_archive = models.BooleanField(default=False,)
    created = models.DateTimeField(auto_now=True,)
    order_num = models.IntegerField()

    def __str__(self):
        return '{} : {}'.format(str(self.pk), self.title)

    # 해당 Task의 순서를 변경합니다.
    def update_order(self, order):
        if self.order_num is order:
            return
        origin_order = self.order_num
        self.order_num = order
        new_order_gt = order > origin_order
        
        tasks = Task.objects.filter(author=self.author)
        for task in tasks:
            if new_order_gt:
                task.order_num = task.order_num - 1
            else:
                task.order_num = task.order_num + 1
            task.save()

        return

    # 특정 회원의 Task를 모두 불러와서 재 정렬합니다.
    def re_order(self):
        pass
    

task/forms.py
from django import forms
from task.models import Task
from django.utils.translation import ugettext_lazy as _

class SimpleTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('title',)
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': _('To Do')})
        }
        labels = {
            'title': ''
        }

class ChangeTaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ("title", "text",)
        labels = {
            'title': _('Title'),
            'text': _('Memo'),
        }

task/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from task.forms import SimpleTaskForm
from task.models import Task, get_max_order_num
from django.utils.translation import ugettext_lazy as _

@login_required
def index(request):
    form = SimpleTaskForm()
    # TODO: 순서를 정하고 정렬하여 보여줘야함
    tasks = Task.objects.all()
    return render(request, 'task/index.html', {'title': _('Welcome'), 'form': form, 'tasks': tasks, })

@login_required
def add(request):
    if request.method == "POST":
        form = SimpleTaskForm(request.POST)
        if form.is_valid:
            task = form.save(commit=False)
            task.author = request.user
            task.order_num = get_max_order_num(request.user) + 1
            task.save()
        return redirect('task:index')
    else:
        pass
    return None

@login_required
def done(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = True
    task.save()
    return redirect('task:index')

@login_required
def delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return redirect('task:index')

@login_required
def incomplete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = False
    task.save()
    return redirect('task:index')

@login_required
def re_order(request, pk, order):
    task = get_object_or_404(Task, pk=pk)
    if order is task.order_num:
        return

    origin_order = task.order
    new_order = order
    task.order_num = new_order

    tasks = get_list_or_404(Task, filter(order__gt=origin_order, order__lte=new_order))

    new_order_is_great = new_order > origin_order

    for item in tasks:
        if new_order_is_great:
            item.order_num = item.order_num - 1
        else:
            item.order_num = item.order_num + 1
        
    return

task/templates/task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'task/css/jquery-ui.min.css' %}">
    {% block header_title %}
    {% endblock header_title %}
</head>
<body>
    {% block content %}
    {% endblock content %}
    
    <script src="{% static 'task/js/jquery.js' %}"></script>
    <script src="{% static 'task/js/jquery-ui.min.js' %}"></script>
</body>
</html>

task/templates/task/index.html
{% include 'task/base.html' %}

{% block header_title %}
<title>{{ _('Welcome') }}</title>
{% endblock header_title %}

{% block content %}
<h1>{{ _('Welcome') }}</h1>
<p>Hello {{ user.username }} <small>(<a href="{% url 'account:logout' %}">Log out</a>)</small></p>
<ul id="sortable" class="todo-list">
    {% for task in tasks %}
    <li>
        <div order="task.order">
        {{ task.title }}
        <a href="{% url 'task:delete' task.id %}">{{ _('Delete') }}</a>
        {% if task.is_done is not True %}
        <a href="{% url 'task:done' task.id %}">{{ _('Done') }}</a>
        {% else %}
        <a href="{% url 'task:incomplete' task.id %}">{{ _('In') }}</a>
        {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

<form action="{% url 'task:add' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{{ _('Submit') }}</button>

<script>
  $( function() {
    $( "#sortable" ).sortable({
        change: function(e, u) {
            console.log('chango');
        },
        stop: function(e, u) {
            console.log('stop');
        },
        start: function(e, u) {
            console.log('start');
        },
        update: function(e, u) {
            console.log('update');
            console.log(u.item);
            console.log(u.position);
            console.log(u.item.);
        }
    });
    $( "#sortable" ).disableSelection();
  } );
  </script>
</form>
{% endblock content %}